server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-service:3306/appdb?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${MYSQL_USER:appuser}
spring.datasource.password=${MYSQL_PASSWORD:apppass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
