apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: appdb
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppass
  MYSQL_ROOT_PASSWORD: rootpass
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/appdb?allowPublicKeyRetrieval=true&useSSL=false
